 
 export const cities = [
  { name: "Ballsh" },
  { name: "Bajram Curri" },
  { name: "Berat" },
  { name: "Bulqizë" },
  { name: "Burrel" },
  { name: "Çorovodë" },
  { name: "Delvinë" },
  { name: "Divjakë" },
  { name: "Durrës" },
  { name: "Elbasan" },
  { name: "Ersekë" },
  { name: "Fier" },
  { name: "Fushë-Arrëz" },
  { name: "Fushë-Krujë" },
  { name: "Gjirokastër" },
  { name: "Gramsh" },
  { name: "Himarë" },
  { name: "Kamëz" },
  { name: "Kavajë" },
  { name: "Këlcyrë" },
  { name: "Korçë" },
  { name: "Krujë" },
  { name: "Kukës" },
  { name: "Laç" },
  { name: "Lezhë" },
  { name: "Librazhd" },
  { name: "Lushnjë" },
  { name: "Maliq" },
  { name: "Memaliaj" },
  { name: "Milot" },
  { name: "Orikum" },
  { name: "Patos" },
  { name: "Peqin" },
  { name: "Peshkopi" },
  { name: "Pogradec" },
  { name: "Poliçan" },
  { name: "Roskovec" },
  { name: "Rrëshen" },
  { name: "Rrogozhinë" },
  { name: "Sarandë" },
  { name: "Selenicë" },
  { name: "Shijak" },
  { name: "Shkodër" },
  { name: "Tepelenë" },
  { name: "Tiranë" },
  { name: "Vau i Dejës" },
  { name: "Vlorë" },
  { name: "Vorë" },
  { name: "Rubik" }
];
